#!/bin/bash

# Create a startup script for an application called sleepwalkingserver. The script should be named sleepwalking and accept "start" and "stop" as arguments. If anything other than "start" or "stop" is provided as an argument, display a usage statement: "Usage sleepwalking start|stop" and terminate the script with an exit status of 1.

# To start sleep­walking­server, use this command: "/tmp/sleep­walking­server &" To stop sleep­walking­server, use this command: "kill $(cat /tmp/sleep­walking­server.pid)"

case "$1" in
   start)
      /tmp/sleepwalkingserver &
      echo "sleepwalkingserver started"
   ;;
   stop)
      kill $(cat /tmp/sleep­walking­server.pid)
      echo "sleepwalkingserver stopped"
   ;;
   *)
      echo "Usage $0 start|stop"
      exit 1
   ;;
esac
